// <auto-generated />
using CarDealershipManager.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealershipManager.Migrations
{
    [DbContext(typeof(CarDealershipDbContext))]
    [Migration("20260319184831_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealershipManager.Models.Entities.AdminModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.BodyTypeModel", b =>
                {
                    b.Property<int>("BodyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyTypeId");

                    b.ToTable("BodyTypes");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.CarModel", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int?>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CarStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrivetrainId")
                        .HasColumnType("int");

                    b.Property<int?>("EuroClassId")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GenerationId")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("CarStatusId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DrivetrainId");

                    b.HasIndex("EuroClassId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("GenerationId");

                    b.HasIndex("TransmissionTypeId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.CarStatusModel", b =>
                {
                    b.Property<int>("CarStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarStatusId");

                    b.ToTable("CarStatusModel");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.ColorModel", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.DrivetrainModel", b =>
                {
                    b.Property<int>("DrivetrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrivetrainId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrivetrainId");

                    b.ToTable("Drivetrains");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.EuroClassModel", b =>
                {
                    b.Property<int>("EuroClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EuroClassId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EuroClassId");

                    b.ToTable("EuroClasses");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.FuelTypeModel", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.GalleryModel", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.HasIndex("CarId");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.GenerationModel", b =>
                {
                    b.Property<int>("GenerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenerationId");

                    b.HasIndex("ModelId");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.MakeModel", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakeId");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.ModelModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.TransmissionTypeModel", b =>
                {
                    b.Property<int>("TransmissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransmissionTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransmissionTypeId");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.CarModel", b =>
                {
                    b.HasOne("CarDealershipManager.Models.Entities.BodyTypeModel", "BodyType")
                        .WithMany("Cars")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarDealershipManager.Models.Entities.CarStatusModel", "CarStatus")
                        .WithMany("Cars")
                        .HasForeignKey("CarStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarDealershipManager.Models.Entities.ColorModel", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarDealershipManager.Models.Entities.DrivetrainModel", "Drivetrain")
                        .WithMany("Cars")
                        .HasForeignKey("DrivetrainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarDealershipManager.Models.Entities.EuroClassModel", "EuroClass")
                        .WithMany("Cars")
                        .HasForeignKey("EuroClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarDealershipManager.Models.Entities.FuelTypeModel", "FuelType")
                        .WithMany("Cars")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarDealershipManager.Models.Entities.GenerationModel", "Generation")
                        .WithMany("Cars")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarDealershipManager.Models.Entities.TransmissionTypeModel", "TransmissionType")
                        .WithMany("Cars")
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("CarStatus");

                    b.Navigation("Color");

                    b.Navigation("Drivetrain");

                    b.Navigation("EuroClass");

                    b.Navigation("FuelType");

                    b.Navigation("Generation");

                    b.Navigation("TransmissionType");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.GalleryModel", b =>
                {
                    b.HasOne("CarDealershipManager.Models.Entities.CarModel", "Car")
                        .WithMany("Gallery")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.GenerationModel", b =>
                {
                    b.HasOne("CarDealershipManager.Models.Entities.ModelModel", "Model")
                        .WithMany("GenerationModel")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.ModelModel", b =>
                {
                    b.HasOne("CarDealershipManager.Models.Entities.MakeModel", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Make");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.BodyTypeModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.CarModel", b =>
                {
                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.CarStatusModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.ColorModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.DrivetrainModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.EuroClassModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.FuelTypeModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.GenerationModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.MakeModel", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.ModelModel", b =>
                {
                    b.Navigation("GenerationModel");
                });

            modelBuilder.Entity("CarDealershipManager.Models.Entities.TransmissionTypeModel", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
